import React from 'react';
import { View, Text, TouchableOpacity, ScrollView } from 'react-native';
// import {Card, Button, Avatar, Grid, Row, Col, ButtonGroup} from 'react-native-elements'

import {Actions} from 'react-native-router-flux';

import styles from '../styles'

export default class Terms extends React.Component {

    render() {
        return(
            <ScrollView style={styles.container}>
                <Text>
                    These Terms of Use are effective on May 26, 2017.</Text>

                    <Text></Text>
                    <Text>Thank you for choosing to use Eligo (“we” “us” “our” or “Eligo”)!</Text>
                    <Text></Text>
                    <Text>By accessing and using the Eligo mobile application, you accept and agree 
                    to the terms and provision of this agreement. In addition, when using Eligo’s 
                    particular services, you shall be subject to any posted guidelines or rules
                     applicable to such services, which may be posted and modified from time to time. 
                     All such guidelines or rules are hereby incorporated by reference into the 
                     Terms of Use.</Text>
            <Text></Text>
            <Text>IF YOU DO NOT AGREE WITH ALL PROVISIONS OF THIS AGREEMENT, PLEASE DO NOT ACCESS 
                AND/OR USE THE SERVICES.</Text>
                <Text></Text>
            <Text>Please review Eligo’s Privacy Policy. The terms of the privacy policy are incorporated 
                into, and considered part of, this agreement.</Text>
            <Text></Text>
            <Text style={{fontWeight: 'bold'}}>CERTAIN DISCLAIMERS</Text>

            <Text>ALL INFORMATION CONTAINED ON THE APPLICATION INCLUDED NUTRIENT INFORMATION, INGREDIENTS, 
                FOOD ALLERGENS, AND INFORMATION RELATING TO MEDICAL AND HEALTH CONDITIONS IS FOR INFORMATIONAL 
                PURPOSES ONLY AND NOT PROVIDED AS MEDICAL ADVICE.</Text>
                <Text></Text>
            <Text>ELIGO DOES NOT ASSUME ANY LIABILITY FOR INACCURACIES OR MISSTATEMENTS ABOUT PRODUCTS, 
                WHETHER BASED ON MANUFACTURER INFORMATION, THIRD PARTY INFORMATION, ELIGO’S USERS’ INFORMATION 
                AND ASSESSMENTS GENERATED BY ELIGO. YOU SHOULD CAREFULLY READ ALL INFORMATION PROVIDED BY THE 
                MANUFACTURERS OF THE PRODUCTS, WHETHER ONLINE OR ON THE ACTUAL PRODUCT PACKAGING AND LABELS, 
                INCLUDING NUTRIENT CONTENT, INGREDIENTS, FOOD ALLERGEN AND CONTACT INFORMATION, AND HEALTH CLAIMS, 
                BEFORE USING OR CONSUMING A PRODUCT. FOR ADDITIONAL INFORMATION ABOUT A PRODUCT, PLEASE CONTACT 
                THE MANUFACTURER.</Text>
                <Text></Text>
            <Text>SHOULD YOU USE THESE SERVICES TO PURCHASE A PRODUCT FOR ANOTHER PERSON, E.G. FAMILY OR ROOMATES, 
                THEY SHOULD ALSO READ ALL INFORMATION PROVIDED BY THE MANUFACTURERS OF THE PRODUCTS. </Text>
                <Text></Text>

            <Text>INFORMATION ON THE SERVICES IS NOT INTENDED AS A SUBSTITUTE FOR THE ADVICE PROVIDED BY A 
                QUALIFIED AND LICENSED HEALTHCARE PROFESSIONAL. YOU SHOULD NOT USE INFORMATION ON THE SERVICES
                 FOR THE DIAGNOSIS OR TREATMENT OF A HEALTH PROBLEM OR DISEASES. YOU SHOULD ALWAYS CONSULT
                  YOUR HEALTHCARE PROVIDER BEFORE MAKING ANY DIETARY OR NUTRITIONAL CHANGES.</Text>
                  <Text></Text>

            <Text>IN ADDITION TO ALL OTHER LIMITATIONS AND DISCLAIMERS IN THIS AGREEMENT, ELIGO DISCLAIMS 
                ANY LIABILITY OR LOSS IN CONNECTION WITH THE CONTENT PROVIDED ON THE SERVICES.</Text>
                <Text></Text>

            <Text style={{fontWeight: 'bold'}}>USER ACCOUNTS </Text>

            <Text>Access use of the application through logging in with a Facebook account. You represent 
                and warrant that: a.) your account’s registration information is truthful and accurate, 
                b) you will maintain the accuracy of such information; and c) your use of the Services does 
                not violate any applicable law or regulation of the terms of this Agreement.</Text>
                <Text></Text>

            <Text>Account Responsibilities. You are responsible for maintaining the confidentiality of your 
                Eligo Account login information and are fully responsible for all activities that occur under 
                your Eligo Account. Elligo cannot and will not be liable for any loss or damage arising from 
                your failure to comply with the above requirements. We will protect your Eligo Account 
                information in accordance with the Privacy Policy.</Text>
                <Text></Text>

            <Text style={{fontWeight: 'bold'}}>SERVICE</Text>

            <Text>Ownership. You acknowledge that all the intellectual property rights in the application’s 
                Services are owned by Eligo. The provision of the Services does not transfer to you or any 
                third party any rights, title or interest in or to such intellectual property rights. Eligo 
                reserves all rights not granted in this Agreement.</Text>
                <Text></Text>

            <Text>License. Subject to the terms of this Agreement, Eligo grants you a non-transferable, 
                non-exclusive, license (without the right to sublicense) to a) use Services for your personal, 
                non-commercial services, and b) install and use the Application solely on your own mobile 
                devices (i.e. iPhone).</Text>
                <Text></Text>

            <Text>Certain Restrictions. The rights granted to you in this Agreement are subject to the following 
                restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, 
                or otherwise commercially exploit the Services; (b) you shall not modify, make derivative works of, 
                disassemble, reverse compile or reverse engineer any part of the Services; (c) you shall not 
                access the Services in order to build a similar or competitive service; (d) except as expressly 
                stated herein, no part of the Services may be copied, reproduced, distributed, republished, 
                downloaded, displayed, posted or transmitted in any form or by any means; (e) You may not copy 
                or modify the code used to provide the Services; and (f) You may not use the Application or 
                Services on or in connection with any other website, for any purpose. Any future release, update, 
                or other addition to functionality of the Services shall be subject to the terms of this Agreement. 
                All copyright and other proprietary notices on the Site must be retained on any copies.</Text>
                <Text></Text>

            <Text>Use of Services at Your Own Risk. Your access to and use of the Application and Services is 
                at your own risk. Eligo will have no responsibility for any harm to your computing system, loss 
                of data, or other harm to you or any third party, including, without limitation, any bodily harm, 
                that results from your access to or use of the Apps or Services, or reliance on any information 
                or advice with respect to any food products. This includes any individuals for whom you purchase 
                products while using Eligo.</Text>
                <Text></Text>

            <Text>Customer Support. Eligo has no obligation to provide you with customer support of any kind. 
                However, Fooducate may provide you with customer support from time to time, at Eligo’s sole discretion.</Text>
                <Text></Text>

            <Text>Modification Of Services. Eligo reserves the right, at any time, to modify, suspend, or discontinue 
                the Services or any part thereof with or without notice. Eligo may modify or remove any Content from 
                the Services at any time without notice to you. Eligo is not liable for any such modification, suspension, 
                discontinuance or removal. You agree that Eligo will not be liable to you or to any third party for 
                any modification, suspension, or discontinuance of the Services or any part thereof.</Text>
                <Text></Text>

            <Text style={{fontWeight: 'bold'}}>ACCEPTABLE USE POLICY</Text>

            <Text>Other Users. Each user of the Service is solely responsible for any and all their User Content. 
                Because we do not control User Content, you acknowledge and agree that we are not responsible for 
                any User Content and we make no guarantees regarding the accuracy, currency, suitability, or quality 
                of any User Content, and we assume no responsibility for any User Content. Your interactions with 
                other Service users are solely between you and such user. You agree that Eligo will not be responsible 
                for any loss or damage incurred as the result of any such interactions. If there is a dispute 
                between you and any Service user, we are under no obligation to become involved.</Text>
                <Text></Text>

            <Text>Release. You hereby release us, our officers, employees, agents and successors from claims, 
                demands any and all losses, damages, rights, claims, and actions of any kind including personal 
                injuries, death, and property damage, that is either directly or indirectly related to or arises 
                from any interactions with or conduct of any App Store, any other Service users, or any Third 
                Party Sites & Ads.</Text>
                <Text></Text>


            <Text style={{fontWeight: 'bold'}}>DISCLAIMERS</Text>

            <Text>THE SERVICES OF THE APPLICATIONS AND USER CONTENT ARE PROVIDED "AS IS", WITHOUT WARRANTY OR 
                CONDITION OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, ELIGO EXPLICITLY 
                DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT 
                OR NON-INFRINGEMENT.</Text>
                <Text></Text>

            <Text>ELIGO MAKES NO WARRANTY THAT THE APP, CONTENT, USER CONTENT OR SERVICES WILL MEET YOUR REQUIREMENTS 
                OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. ELIGO MAKES NO WARRANTY REGARDING 
                THE QUALITY OF ANY PRODUCTS, SERVICES, OR INFORMATION OBTAINED THROUGH THE APP, CONTENT, USER CONTENT 
                OR SERVICES, OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY INFORMATION 
                OBTAINED THROUGH THE APP, CONTENT, USER CONTENT OR SERVICES, INCLUDING, WITHOUT LIMITATION, ANY 
                INFORMATION OR ADVICE WITH RESPECT TO ANY FOOD PRODUCT. ELIGO DOES NOT REGULARLY MONITOR OR UPDATE 
                THE ACCURACY OR RELIABILITY OF THE CONTENT OR USER CONTENT.</Text>
                <Text></Text>

            <Text>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM ELIGO OR THROUGH THE APP, CONTENT, 
                USER CONTENT OR SERVICES, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN OR CREATE ANY LIABILITY 
                ON THE PART OF ELIGO.</Text>
                <Text></Text>

            <Text>THE APP, CONTENT, USER CONTENT AND SERVICES ARE FOR CONSUMER EDUCATIONAL USE ONLY. NOTHING CONTAINED 
                IN THE SERVICES IS OR SHOULD BE CONSIDERED, OR USED AS A SUBSTITUTE FOR, MEDICAL, NUTRITIONAL OR ANY 
                OTHER PROFESSIONAL ADVICE, DIAGNOSIS OR TREATMENT. THIS SITE, APPS, CONTENT AND THE SERVICES DO NOT 
                CONSTITUTE THE PRACTICE OF ANY MEDICAL, NUTRITIONAL, DIETETIC, NURSING OR OTHER PROFESSIONAL HEALTH 
                CARE ADVICE, DIAGNOSIS OR TREATMENT. ELIGO ADVISES USERS TO ALWAYS SEEK THE ADVICE OF A PHYSICIAN OR 
                OTHER QUALIFIED, LICENSED HEALTH CARE PROVIDER WITH ANY QUESTIONS REGARDING PERSONAL HEALTH, NUTRITION 
                OR MEDICAL CONDITIONS. NEVER DISREGARD, AVOID OR DELAY IN OBTAINING MEDICAL ADVICE FROM YOUR DOCTOR OR 
                OTHER QUALIFIED, LICENSED HEALTH CARE PROVIDER BECAUSE OF SOMETHING YOU HAVE READ ON THE APP. ELIGO MAKES 
                NO REPRESENTATIONS OR WARRANTIES ABOUT THE INFORMATION, TOOLS, OR CONTENT INCLUDED IN THE APP, CONTENT, 
                USER CONTENT OR SERVICES.</Text>
                <Text></Text>

            <Text>PLEASE ALSO REVIEW THE SPECIFIC DISCLAIMERS IN SECTION “CERTAIN DISCLAIMERS”.</Text>
            <Text></Text>

            <Text style={{fontWeight: 'bold'}}>INDEMNITY</Text>

            <Text>You agree to indemnify and hold Eligo, its successors, subsidiaries, affiliates, any related 
                companies, licensors and partners, and the officers, directors, employees, agents and representatives 
                of each of them harmless, including costs and attorney's' fees, from any claim or demand made by any 
                third party due to or arising out of (a) your use of the Services, (b) your User Content, or (c) your 
                violation of this Agreement. Eligo reserves the right, at your expense, to assume the exclusive 
                defense and control of any matter for which you are required to indemnify us and you agree to cooperate 
                with our defense of these claims. You agree not to settle any matter without the prior written 
                consent of Eligo. Eligo will use reasonable efforts to notify you of any such claim, action or 
                proceeding upon becoming aware of it.</Text>
                <Text></Text>

             <Text style={{fontWeight: 'bold'}}>TERM AND TERMINATION</Text>

            <Text>If you violate any of these Terms of Service, your permission to use the App, Content, 
                and Services will automatically terminate. Eligo reserves the right to revoke your access to and 
                use of the App, Content, and Services at any time, with or without cause.</Text>
                <Text></Text>

            <Text style={{fontWeight: 'bold'}}>GENERAL</Text>

            <Text>Changes to Terms of Service. You acknowledge and agree that Eligo may revise these Terms of Service 
                from time to time. By continuing to access or use the Site, Content, or Services after Eligo makes any 
                such revision, you agree to be bound by the revised Terms of Service.</Text>
                <Text></Text>

            <Text>Severability. In the event that any provision of these Terms of Service is held to be invalid or 
                unenforceable, the remaining provisions of these Terms of Service will remain in full force and effect.</Text>
                <Text></Text>

            <Text>Waiver. The failure of Eligo to enforce any right or provision of these Terms of Service will not be deemed 
                a waiver of such right or provision.</Text>
                <Text></Text>

            <Text>Governing Law. This Agreement shall be governed by the laws of the State of Israel without giving effect 
                to any conflict of laws principles that may provide the application of the law of another jurisdiction. 
                Notwithstanding the foregoing, we may seek injunctive or other equitable relief to protect our intellectual 
                property rights in any court of competent jurisdiction.</Text>
                <Text></Text>

            <Text>Entire Agreement. This Agreement (which includes the Privacy Policy and any other rules posted on the 
                Site or Apps) constitute the entire and exclusive agreement between Eligo and you regarding the App, 
                Content, User Content, and Services, and these Terms of Service supersede and replace any prior agreements 
                between Eligo and you regarding the App, Content, and Services. If any provision of this Agreement is, for 
                any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired 
                and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to 
                the maximum extent permitted by law. This Agreement, and your rights and obligations herein, may not be 
                assigned, subcontracted, delegated, or otherwise transferred by you without Eligo’s prior written consent, 
                and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be 
                null and void. The terms of this Agreement shall be binding upon assignees.</Text>
                <Text></Text>

            <Text>Any questions about this Privacy Policy should be addressed to teameligo@gmail.com</Text>
            </ScrollView>
      );
    }
}
